import type {Metadata} from 'next';import Header from '../../components/Header';import Footer from '../../components/Footer';
export const metadata:Metadata={title:'Terms & Conditions',description:'Terms and conditions for participation in Banking CEE Network events.'};
const Section=({title,children}:{title:string;children:React.ReactNode})=><section><h2>{title}</h2>{children}</section>;
export default function Page(){return <main className="legal-page"><div className="legal-hero"><Header/><div className="shell"><p className="eyebrow">Legal</p><h1>Terms &amp; Conditions</h1><p>Terms applying to participation in Banking CEE Network events and related activities organised by CONNECTIVA s.r.o.</p></div></div><div className="shell legal-content">
<Section title="1. About These Terms"><p>These Terms apply to events, conferences and related activities organised by CONNECTIVA s.r.o. under the Banking CEE Network, including Banking CEE Expo and Digital Banking CEE Summit. Event-specific information such as dates, venue, programme and participation arrangements is published on the relevant event page or communicated directly to participants.</p></Section>
<Section title="2. Organiser"><p>The organiser is CONNECTIVA s.r.o., company registration number 09821571, Prague, Czech Republic.</p></Section>
<Section title="3. Attendance Requests & Eligibility"><p>Attendance may be subject to eligibility criteria determined by the Organiser. Complimentary attendance may be offered to qualifying representatives of banks, financial institutions, regulatory authorities and other eligible organisations. Submission of an attendance request does not confirm attendance. A place is confirmed only after approval and completion of any required registration process.</p></Section>
<Section title="4. Technology & Solution Providers"><p>Participation by technology providers, solution providers and other commercial organisations may be available through sponsorship, partnership or other commercial arrangements. Submission of an attendance request does not guarantee complimentary participation. The Organiser may contact such organisations regarding relevant partnership opportunities.</p></Section>
<Section title="5. Registration Information"><p>Participants must provide accurate and up-to-date information. Registration may be personal and non-transferable unless otherwise agreed. The Organiser may refuse or revoke registration where information is materially inaccurate or eligibility criteria are not met.</p></Section>
<Section title="6. Programme & Event Changes"><p>Programmes, speakers, topics, timings, venues and formats are subject to change. The Organiser may make reasonable substitutions, amendments, postponements or format changes where necessary and will make reasonable efforts to notify registered participants of material changes.</p></Section>
<Section title="7. Cancellation or Postponement"><p>If an event is postponed or cancelled, the Organiser will notify registered participants as reasonably practicable. Unless expressly agreed otherwise, the Organiser is not responsible for travel, accommodation or other participant costs. Commercial rights for sponsors and partners are governed by the applicable commercial agreement.</p></Section>
<Section title="8. Conduct"><p>All participants are expected to behave professionally and respectfully. Harassment, discrimination, abusive behaviour, disruption, unauthorised solicitation or other inappropriate conduct may result in removal from an event or exclusion from future Connectiva events.</p></Section>
<Section title="9. Event Access"><p>Participants must comply with venue rules, security requirements and reasonable instructions from the Organiser. Event badges or credentials may not be shared or transferred without approval.</p></Section>
<Section title="10. Photography, Video & Recording"><p>Photography, filming and audio recording may take place during events. Participants may appear incidentally in event photography or recordings used for event documentation and promotion. Recording of presentations or sessions by attendees may be restricted.</p></Section>
<Section title="11. Intellectual Property"><p>Event materials, branding, presentations and other content remain the intellectual property of the Organiser, speakers or respective rights holders. Materials may not be reproduced, distributed or commercially used without appropriate permission.</p></Section>
<Section title="12. Speakers & Contributors"><p>Expressing interest in speaking does not guarantee participation. Speaker and contributor participation is subject to confirmation by the Organiser. Confirmed speakers may be required to provide additional information and materials under separate arrangements.</p></Section>
<Section title="13. Sponsors & Partners"><p>Sponsorship and partnership rights, benefits, fees, cancellation arrangements and payment terms are governed by the relevant agreement, order form, invoice or written confirmation. Where those terms conflict with these general Terms, the specific commercial agreement will prevail for that arrangement.</p></Section>
<Section title="14. Liability & Force Majeure"><p>To the extent permitted by applicable law, the Organiser will not be liable for indirect or consequential losses arising from participation in or inability to attend an event. The Organiser is not responsible for failure or delay caused by circumstances outside its reasonable control. Nothing in these Terms excludes liability that cannot legally be excluded.</p></Section>
<Section title="15. Personal Data"><p>Personal data is processed in accordance with the Banking CEE <a href="/privacy-policy">Privacy Policy</a>.</p></Section>
<Section title="16. Changes & Contact"><p>We may update these Terms from time to time. For questions, contact <a href="mailto:info@bancee.eu">info@bancee.eu</a>.</p></Section>
</div><Footer/></main>}
