import type {Metadata} from 'next';import Header from '../../components/Header';import Footer from '../../components/Footer';
export const metadata:Metadata={title:'Privacy Policy',description:'Privacy information for the Banking CEE Network and Connectiva events.'};
const Section=({title,children}:{title:string;children:React.ReactNode})=><section><h2>{title}</h2>{children}</section>;
export default function Page(){return <main className="legal-page"><div className="legal-hero"><Header/><div className="shell"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p>How CONNECTIVA s.r.o. collects, uses and protects personal data in connection with the Banking CEE Network, our events and related services.</p></div></div><div className="shell legal-content">
<Section title="1. Who We Are"><p>CONNECTIVA s.r.o. (“Connectiva”, “we”, “us”, “our”) is the organiser behind the Banking CEE Network. CONNECTIVA s.r.o. is registered in the Czech Republic under company registration number 09821571, with registered office in Prague, Czech Republic. For applicable data-protection law, including the GDPR, CONNECTIVA s.r.o. acts as data controller.</p></Section>
<Section title="2. Who This Policy Applies To"><p>This policy applies to people who visit our websites, request or register to attend an event, express interest in speaking, represent sponsors or prospective partners, subscribe to updates, contact us, participate as speakers or moderators, or use event and networking services.</p></Section>
<Section title="3. Personal Data We Collect"><p>Depending on your interaction with us, we may collect identity and professional data such as name, job title, company, country, business email, telephone number, company website and LinkedIn URL; event participation data such as event interest, attendance status, attendance days, professional interests, participation goals and networking preferences; event profile data such as a professional photo, short biography and profile-visibility preferences; speaker-interest data such as expertise and proposed topics; partnership data such as event interest, objectives and areas of expertise; and technical information such as referrer, campaign/UTM data and analytics information.</p></Section>
<Section title="4. How We Collect Data"><p>We may collect data when you complete a website form, request attendance, complete event registration, submit a partnership or speaker enquiry, subscribe to updates, communicate with us by email, phone or social media, participate in an event, enter a commercial relationship, or interact with our websites and campaigns.</p></Section>
<Section title="5. Why We Use Personal Data"><p>We use personal data to review attendance requests, manage event registration and participation, communicate operational event information, facilitate networking, respond to enquiries, manage partnerships and sponsorships, improve our events and services, maintain security, meet legal and accounting requirements, and send marketing communications where permitted.</p></Section>
<Section title="6. Legal Bases"><p>Depending on the activity, we rely on contract, legitimate interests, consent and/or legal obligation as the appropriate legal basis for processing.</p></Section>
<Section title="7. Attendance Requests & Registration"><p>Submitting an attendance request does not confirm registration. We use professional information to assess eligibility. If approved, you may receive a secure link to complete registration. Registration information may be used to administer participation, understand professional interests and support relevant networking.</p></Section>
<Section title="8. Event Profiles & Networking Tools"><p>Where event networking tools are available, you may choose to make selected professional profile information visible to other registered participants. This may include your name, job title, company, country, interests, photograph and biography.</p></Section>
<Section title="9. Photography, Video & Recording"><p>Photography, video and audio recording may take place at Connectiva events. Such materials may be used for event documentation, communications and promotion, subject to applicable law and any additional notices or consents that may be required.</p></Section>
<Section title="10. Sharing Data"><p>We may share limited professional information where necessary for event delivery, networking or legitimate business purposes and where an appropriate legal basis exists. We do not sell personal contact data. Where contact information is proposed to be shared with a third party for that party’s own marketing, we will do so only where permitted and, where required, with consent.</p></Section>
<Section title="11. Service Providers & International Transfers"><p>We use third-party providers for services such as website hosting, cloud storage, CRM, event technology, analytics, communications, email and technical support. Where personal data is processed outside the EEA, appropriate safeguards required by applicable law are used.</p></Section>
<Section title="12. Retention & Security"><p>We retain personal data only for as long as reasonably necessary for the purposes for which it was collected and to meet legal, accounting and contractual obligations. We use reasonable technical and organisational measures to protect personal data and restrict access to authorised personnel and service providers.</p></Section>
<Section title="13. Your Rights"><p>Subject to applicable law, you may have rights of access, rectification, erasure, restriction, objection, portability and withdrawal of consent. Withdrawal of consent does not affect processing that was lawful before withdrawal.</p></Section>
<Section title="14. Marketing Communications"><p>You can unsubscribe from marketing communications at any time. Unsubscribing from marketing does not prevent us from sending operational communications required for an event or service you have requested.</p></Section>
<Section title="15. Contact"><p>For Banking CEE privacy questions, contact <a href="mailto:info@bancee.eu">info@bancee.eu</a>.</p></Section>
</div><Footer/></main>}
