'use client';
import {FormEvent,useEffect,useState} from 'react';
export default function NewsletterForm(){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle'); const [message,setMessage]=useState(''); const [tracking,setTracking]=useState<Record<string,string>>({});
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setTracking({source:'insights-newsletter',sourcePage:window.location.pathname,utmSource:q.get('utm_source')||'',utmMedium:q.get('utm_medium')||'',utmCampaign:q.get('utm_campaign')||'',referrer:document.referrer||''})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState('sending');setMessage('');const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form).entries());try{const r=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...raw,...tracking})});const b=await r.json();if(!r.ok){setState('error');setMessage(b.error||'We could not subscribe you. Please try again.');return}setState('success');setMessage(b.message||'Thank you for staying connected.');form.reset()}catch{setState('error');setMessage('We could not subscribe you. Please try again.')}}
 if(state==='success')return <div className="newsletter-form newsletter-success"><strong>Thank you for staying connected.</strong><small>{message}</small></div>;
 return <form className="newsletter-form" onSubmit={submit}><div><input name="email" type="email" required placeholder="YOUR EMAIL ADDRESS" aria-label="Your email address"/><button type="submit" disabled={state==='sending'}>{state==='sending'?'SUBSCRIBING…':'STAY CONNECTED →'}</button></div><label className="newsletter-consent"><input name="consent" value="accepted" type="checkbox" required/><small>I agree to receive Banking CEE communications and acknowledge the <a href="/privacy-policy" target="_blank">Privacy Policy</a>. I can unsubscribe at any time.</small></label>{state==='error'&&<small className="form-error">{message}</small>}</form>;
}
