'use client';
import {FormEvent,useEffect,useState} from 'react';
const interests=['Core Banking, Digital Transformation & Infrastructure','AI, Data & Automation','Payments & Transaction Banking','Cybersecurity, Fraud & Digital Identity','Customer Experience & Digital Engagement','Lending & Credit Transformation','Risk, Regulation & Banking Strategy','Other'];
const goals=['Gaining Knowledge & Exploring Industry Trends','Advancing Career Growth','Networking & Building Partnerships','Other'];
type Props={mode:'public'|'token'|'campaign'|'speaker'|'speaker-invite'|'allocation';tokenOrCode?:string;event:string;initial?:Record<string,string>;campaignName?:string;source?:string};
function MultiSelect({label,options,value,onChange}:{label:string;options:string[];value:string[];onChange:(v:string[])=>void}){const [open,setOpen]=useState(false);const toggle=(x:string)=>onChange(value.includes(x)?value.filter(v=>v!==x):[...value,x]);return <div className="multi-select"><button type="button" className="multi-select-trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span>{value.length?`${value.length} selected`:label}</span><b>{open?'−':'+'}</b></button>{open&&<div className="multi-select-menu">{options.map(x=><label key={x}><input type="checkbox" checked={value.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div>}{value.length>0&&<div className="selection-tags">{value.map(x=><button type="button" key={x} onClick={()=>toggle(x)}>{x}<span>×</span></button>)}</div>}</div>}
export default function RegistrationForm({mode,tokenOrCode='',event,initial={},campaignName,source}:Props){
 const [photoFile,setPhotoFile]=useState<File|null>(null);
 const [tracking,setTracking]=useState<Record<string,string>>({});
 useEffect(()=>{const qs=new URLSearchParams(window.location.search);setTracking({source:source||qs.get('source')||(mode==='public'?'direct-registration':'registration'),utmSource:qs.get('utm_source')||'',utmMedium:qs.get('utm_medium')||'',utmCampaign:qs.get('utm_campaign')||'',referrer:document.referrer||''})},[mode,source]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);const [data,setData]=useState<any>({...initial,interests:[],goals:[],company1:'',company2:'',company3:'',profileMethod:'manual',bio:'',profileVisible:false,attendanceDays:'',gala:'',heardAbout:'',marketing:false,privacy:false,linkedin:initial.linkedin||''});const set=(k:string,v:any)=>setData((d:any)=>({...d,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();if(!data.privacy){setError('Please accept the Privacy Policy to confirm your registration.');return}if(data.profileMethod==='linkedin'&&!data.linkedin){setError('Please add your LinkedIn profile URL if you choose LinkedIn as your profile reference.');return}setBusy(true);setError('');try{let photoUrl=data.photoUrl||'';if(data.profileMethod==='manual'&&photoFile){const fd=new FormData();fd.append('file',photoFile);fd.append('event',event);const upload=await fetch('/api/registration/photo',{method:'POST',body:fd});const uploaded=await upload.json();if(!upload.ok){setError(uploaded.error||'The photo could not be uploaded.');setBusy(false);return}photoUrl=uploaded.photoUrl||'';}const res=await fetch('/api/registration/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,tokenOrCode,event,...data,photoUrl,...tracking})});const body=await res.json();if(!res.ok){setError(body.error||'Registration could not be completed.')}else setDone(true)}catch{setError('Registration could not be completed. Please try again.')}finally{setBusy(false)}}
 if(done)return <div className="registration-confirmed"><span>Registration confirmed ✓</span><h2>We Look Forward to Welcoming You.</h2><p>Your registration for <strong>{event==='expo-2026'?'Banking CEE Expo 2026':'Digital Banking CEE Summit 2027'}</strong> is confirmed. A confirmation will be sent to <strong>{data.email}</strong>.</p>{event==='expo-2026'&&<a className="btn registration-dark-btn" href="/expo">Explore the Expo →</a>}</div>;
 return <form className="registration-form premium-registration" onSubmit={submit}>
  <div className="registration-status"><span>{mode==='public'?'Direct invitation':'Attendance approved ✓'}</span><b>Complete registration</b><span>Confirmed</span></div>{campaignName&&<div className="campaign-note"><strong>{campaignName}</strong><span>Controlled registration invitation</span></div>}
  <section><div className="form-section-number">01</div><div><p className="eyebrow dark">Your Details</p><h2>Review Your Professional Information.</h2><div className="partnership-fields">{[['firstName','First Name*'],['lastName','Last Name*'],['jobTitle','Job Title*'],['organisation','Company / Organisation*'],['email','Business Email*'],['country','Country*'],['mobile','Phone Number*'],['website','Company Website']].map(([k,l])=><label key={k}><span>{l}</span><input required={l.includes('*')} type={k==='email'?'email':k==='website'?'url':'text'} value={data[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}</div></div></section>
  <section><div className="form-section-number">02</div><div><p className="eyebrow dark">Interests & Goals</p><h2>Help Us Make Your Experience Relevant.</h2><div className="registration-select-grid"><div><span className="form-label">Areas most relevant to your role</span><MultiSelect label="Select areas" options={interests} value={data.interests} onChange={v=>set('interests',v)}/></div><div><span className="form-label">Main goals for participation</span><MultiSelect label="Select goals" options={goals} value={data.goals} onChange={v=>set('goals',v)}/></div></div><div className="companies-to-meet"><span className="form-label">Are there specific solution providers or companies you would particularly like to meet? <em>Optional</em></span><div className="partnership-fields"><input placeholder="Company 1" value={data.company1} onChange={e=>set('company1',e.target.value)}/><input placeholder="Company 2" value={data.company2} onChange={e=>set('company2',e.target.value)}/><input placeholder="Company 3" value={data.company3} onChange={e=>set('company3',e.target.value)}/></div></div></div></section>
  <section><div className="form-section-number">03</div><div><p className="eyebrow dark">Your Event Profile</p><h2>Help Other Attendees Know Who They&apos;re Meeting.</h2><div className="profile-method-grid"><button type="button" className={data.profileMethod==='manual'?'selected':''} onClick={()=>set('profileMethod','manual')}><strong>Upload my photo & bio</strong><span>Create your profile directly.</span></button><button type="button" className={data.profileMethod==='linkedin'?'selected':''} onClick={()=>set('profileMethod','linkedin')}><strong>Use my LinkedIn profile as reference</strong><span>LinkedIn URL becomes required.</span></button></div>{data.profileMethod==='manual'?<div className="profile-manual"><label><span className="form-label">Professional headshot <em>Optional</em></span><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]||null;setPhotoFile(f);set('profilePhotoFileName',f?.name||'')}}/></label><label><span className="form-label">Short bio <em>Optional</em></span><textarea rows={4} maxLength={500} value={data.bio} onChange={e=>set('bio',e.target.value)} placeholder="A short professional introduction for your attendee profile."/></label></div>:<div className="linkedin-reference"><label><span className="form-label">LinkedIn Profile URL*</span><input required type="url" value={data.linkedin} onChange={e=>set('linkedin',e.target.value)} placeholder="https://www.linkedin.com/in/..."/></label><label className="consent-line"><input type="checkbox" required/><span>I authorise Connectiva to use the professional information available on my LinkedIn profile as a reference when preparing my attendee profile.</span></label></div>}<label className="consent-line"><input type="checkbox" checked={data.profileVisible} onChange={e=>set('profileVisible',e.target.checked)}/><span>I agree for my professional attendee profile to be visible to other registered participants through the Banking CEE event platform/networking tools.</span></label></div></section>
  <section><div className="form-section-number">04</div><div><p className="eyebrow dark">Your Attendance</p><h2>Confirm Your Participation.</h2>{event==='expo-2026'&&<><div className="option-group"><span className="form-label">Which days will you attend?*</span><div className="radio-card-grid">{[['day1','Day 1 — 19 November'],['day2','Day 2 — 20 November'],['both','Both Days']].map(([v,l])=><label key={v} className={data.attendanceDays===v?'selected':''}><input type="radio" name="attendanceDays" value={v} required checked={data.attendanceDays===v} onChange={()=>set('attendanceDays',v)}/><span>{l}</span></label>)}</div></div><div className="option-group"><span className="form-label">Will you join the Cocktail Reception & Gala Dinner on 19 November?</span><div className="radio-card-grid compact">{['Yes','No','Not sure yet'].map(v=><label key={v} className={data.gala===v?'selected':''}><input type="radio" name="gala" value={v} checked={data.gala===v} onChange={()=>set('gala',v)}/><span>{v}</span></label>)}</div></div></>}<label><span className="form-label">Where did you hear about {event==='expo-2026'?'BANCEE26':'the Digital Banking CEE Summit'}?*</span><select required value={data.heardAbout} onChange={e=>set('heardAbout',e.target.value)}><option value="">Select one</option><option>LinkedIn</option><option>Email campaign</option><option>Previous attendee</option><option>Referred by colleague</option><option>Event partner / sponsor</option><option>Other</option></select></label></div></section>
  <section><div className="form-section-number">05</div><div><p className="eyebrow dark">Confirmation</p><h2>Confirm Your Registration.</h2><label className="consent-line"><input type="checkbox" required checked={data.privacy} onChange={e=>set('privacy',e.target.checked)}/><span>I have read and agree to the <a href="/privacy-policy" target="_blank">Privacy Policy</a> and consent to the processing of my information for the administration of my participation.</span></label><label className="consent-line"><input type="checkbox" checked={data.marketing} onChange={e=>set('marketing',e.target.checked)}/><span>I would like to receive updates about future Banking CEE Network events and activities.</span></label>{error&&<p className="form-error">{error}</p>}<button className="partnership-submit" disabled={busy}>{busy?'CONFIRMING…':'CONFIRM MY REGISTRATION →'}</button></div></section>
 </form>;
}
