'use client';
import {FormEvent,useEffect,useState} from 'react';
type Props={event:'expo-2026'|'summit-2027';compact?:boolean;variant?:'network'|'expo'|'summit';source?:string};
export default function RequestAttendanceForm({event,compact=false,variant='network',source}:Props){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');const [message,setMessage]=useState('');const [tracking,setTracking]=useState<Record<string,string>>({});
 useEffect(()=>{const qs=new URLSearchParams(window.location.search);setTracking({utmSource:qs.get('utm_source')||'',utmMedium:qs.get('utm_medium')||'',utmCampaign:qs.get('utm_campaign')||'',referrer:document.referrer||'',source:source||qs.get('source')||(compact?`${variant}-page`:'request-attendance-page')})},[compact,source,variant]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState('sending');setMessage('');const form=e.currentTarget;const payload={...Object.fromEntries(new FormData(form).entries()),event,...tracking};try{const res=await fetch('/api/attendance/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(res.ok){setState('success');setMessage(data.message||'Your request has been received.');form.reset()}else{setState('error');setMessage(data.error||'Something went wrong. Please try again.')}}catch{setState('error');setMessage('We could not submit your request. Please try again.')}}
 if(state==='success')return <div className={`request-success request-success-${variant}`}><span>Request received</span><strong>Thank you for your interest.</strong><p>{message}</p><small>Submitting a request does not confirm attendance. Our team will review your details and contact you shortly.</small></div>;
 return <form className={`${compact?'request-mini-form':'request-full-form'} request-form-${variant}`} onSubmit={submit}>
  <label><span>First Name*</span><input name="firstName" required autoComplete="given-name"/></label><label><span>Last Name*</span><input name="lastName" required autoComplete="family-name"/></label><label><span>Job Title*</span><input name="jobTitle" required autoComplete="organization-title"/></label><label><span>Company / Organisation*</span><input name="organisation" required autoComplete="organization"/></label><label><span>Business Email*</span><input name="email" type="email" required autoComplete="email"/></label><label><span>Country*</span><input name="country" required autoComplete="country-name"/></label>
  <label className="form-wide consent-line"><input name="privacy" value="accepted" type="checkbox" required/><span>I acknowledge the <a href="/privacy-policy" target="_blank">Privacy Policy</a> and understand that Connectiva will process my information to review and respond to my attendance request.</span></label>
  <p className="form-wide request-disclaimer">Complimentary attendance is available to qualifying representatives of banks, financial institutions and regulatory authorities. Submission does not confirm your place.</p>
  <button disabled={state==='sending'} type="submit">{state==='sending'?'Submitting…':'Request Attendance →'}</button>{state==='error'&&<p className="form-error form-wide">{message}</p>}
 </form>;
}
