import type {Metadata} from 'next';
import Header from '../../components/Header';import Footer from '../../components/Footer';import NewsletterForm from '../../components/NewsletterForm';
export const metadata:Metadata={title:'Banking CEE Insights',description:'Interviews, perspectives and conversations from across the Banking CEE community.'};
const showInterviews=false;
const interviews=[
 {title:'Interview 01',speaker:'Speaker Name',role:'Job Title',company:'Company',duration:'00:00',thumbnail:'/images/summit-2026-panel.jpg',url:'#'},
 {title:'Interview 02',speaker:'Speaker Name',role:'Job Title',company:'Company',duration:'00:00',thumbnail:'/images/summit-2026-keynote.jpg',url:'#'},
 {title:'Interview 03',speaker:'Speaker Name',role:'Job Title',company:'Company',duration:'00:00',thumbnail:'/images/summit-2026-community.jpg',url:'#'}
];
export default function Insights(){return <main className="inner-page insights-page"><section className="insights-hero"><Header activePage="insights"/><div className="shell insights-hero-content"><p className="eyebrow">Banking CEE Insights</p><h1>Conversations With the Banking CEE Community.</h1><p>Interviews, perspectives and discussions with banking leaders from across Central &amp; Eastern Europe.</p></div></section>
<section className="section-white insights-explore"><div className="shell">{showInterviews?<><p className="eyebrow dark">Latest Interviews</p><h2>Perspectives From Our Recent Banking CEE Gatherings.</h2><div className="interview-grid">{interviews.map(x=><article key={x.title}><div className="interview-thumb" style={{backgroundImage:`linear-gradient(0deg,rgba(5,25,48,.72),rgba(5,25,48,.08)),url(${x.thumbnail})`}}><span>{x.duration}</span></div><div><p>{x.speaker} · {x.company}</p><h3>{x.title}</h3><small>{x.role}</small><a href={x.url}>Watch Interview →</a></div></article>)}</div></>:<div className="insights-coming-soon"><span>Coming Soon</span><h2>Executive Interviews From the Digital Banking CEE Summit.</h2><p>We are preparing three new conversations from our recent May gathering in Bucharest. The full interview series will be published here shortly.</p><div className="coming-soon-lines"><i/><i/><i/></div></div>}</div></section>
<section className="insights-newsletter" id="newsletter"><div className="shell newsletter-layout"><div><p className="eyebrow dark">Stay Connected</p><h2>Banking CEE Insights, Direct to Your Inbox.</h2><p>Stay connected with the latest perspectives, conversations and updates from across the Banking CEE community.</p></div><NewsletterForm/></div></section><Footer/></main>}
