import type {Metadata} from 'next';
import AgendaClient from '../../../components/AgendaClient';
import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import {getExpoAgenda} from '../../../lib/agenda';
export const metadata:Metadata={title:'Banking CEE Expo 2026 Agenda',description:'Detailed agenda for Banking CEE Expo 2026 in Prague.',robots:{index:false,follow:false}};export const dynamic='force-dynamic';
export default async function Page(){const days=await getExpoAgenda();return <main className="expo-agenda-page"><section className="agenda-hero"><Header activePage="expo" ctaLabel="Request Attendance" ctaHref="/request-attendance?event=expo-2026&source=agenda-header"/>
<div className="shell agenda-hero-inner">
    <p className="eyebrow">5th Annual Banking CEE Expo</p><h1>Explore the 2026 Agenda.</h1>
    <p>Two days of strategic discussions, practical case studies and peer-level conversations bringing together banking leaders, regulators and selected technology partners from across Central &amp; Eastern Europe.</p>
    <div className="agenda-event-meta">19–20 November 2026 · Prague, Czechia</div>
    <div className="agenda-cover-stats"><div><strong>250+</strong>
    <span>Attendees</span></div><div><strong>50+</strong>
    <span>Speakers</span></div><div><strong>3</strong><span>Stages</span></div><div><strong>18+</strong><span>Hours of Content</span></div><div><strong>20+</strong><span>CEE Countries</span></div></div><div className="actions agenda-cover-actions"><a className="btn btn-primary agenda-attend-btn" href="/request-attendance?event=expo-2026&source=agenda">Request Complimentary Attendance</a><a className="btn btn-ghost agenda-explore-btn" href="/expo">Explore the Expo</a></div><p className="agenda-eligibility">Complimentary attendance is available for qualifying representatives of banks, financial institutions and regulatory authorities.</p></div></section><section className="agenda-programme section-light"><div className="shell"><AgendaClient days={days}/></div></section><a className="agenda-mid-cta" href="/request-attendance?event=expo-2026&source=agenda-mid"><div className="shell"><span>Interested in joining these discussions in Prague?</span><strong>Complimentary attendance is available for qualifying banking professionals and regulators.</strong><b>Request Attendance →</b></div></a><section className="agenda-discover section-white"><div className="shell"><p className="eyebrow dark">Discover Banking CEE Expo 2026</p><h2 className="section-heading-lines"><span>Continue Exploring</span><span>the Event.</span></h2><div className="agenda-discover-links"><a href="/expo#speakers"><span>Who will I meet?</span><strong>View Speakers →</strong></a><a href="/#advisory-board"><span>Who helps shape the programme?</span><strong>Meet the Advisory Board →</strong></a><a href="/expo#sponsors"><span>Which companies are involved?</span><strong>Explore Partners →</strong></a></div></div></section><section className="agenda-next section-navy"><div className="shell"><p className="eyebrow">Your Next Step</p><h2 className="section-heading-lines"><span>Choose the Next Step</span><span>That Fits You.</span></h2><div className="agenda-next-grid"><a className="agenda-next-card explore" href="/expo"><span>Explore</span><h3>Explore the Expo</h3><p>Discover the speakers, community, networking and overall Expo experience.</p><b>Explore the Expo →</b></a><a className="agenda-next-card attend" href="/request-attendance?event=expo-2026&source=agenda-bottom"><span>Attend</span><h3>Attend the Expo</h3><p>Represent a bank, financial institution or regulator? Complimentary attendance is available for qualifying professionals.</p><b>Request Complimentary Attendance →</b></a><a className="agenda-next-card partner" href="/partnership-enquiry?event=expo-2026&source=agenda-bottom"><span>Partner</span><h3>Partner With Us</h3><p>Represent a technology or solution provider? Explore opportunities to engage with banking decision-makers across CEE.</p><b>Explore Partnerships →</b></a></div></div></section><Footer/></main>}
