import Image from 'next/image';
import type {Metadata} from 'next';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import PartnerLogoGrid from '../../components/PartnerLogoGrid';
import BankLogoGrid from '../../components/BankLogoGrid';
import AudienceSplit from '../../components/AudienceSplit';
export const metadata:Metadata={title:'Partner With Banking CEE',description:'Explore partnership opportunities across Banking CEE Expo, Digital Banking CEE Summit, tailored events and webinars.'};

export default function Partners(){return <main className="inner-page partners-page">
  <section className="partner-hero"><Header ctaLabel="Explore Partnerships" activePage="partners" ctaHref="#partnership-options"/><div className="shell partner-hero-content"><p className="eyebrow">Partner With Banking CEE</p><h1>Build Meaningful Relationships With Banking Leaders Across CEE.</h1><p>Connect your organisation with senior banking decision-makers through flagship events, tailored experiences and year-round opportunities designed around meaningful industry engagement.</p><a className="btn btn-primary" href="#partnership-options">Explore Partnership Opportunities ↓</a><div className="partner-hero-line">FLAGSHIP EVENTS · TAILORED EVENTS · WEBINARS</div></div></section>

  <section className="section-white"><div className="shell"><div className="partner-intro"><div><p className="eyebrow dark">Participation by Design</p><h2 className="section-heading-lines"><span>Bringing the Right</span><span>People Together.</span></h2></div><p>Banking CEE is designed around a carefully balanced audience so technology partners can engage with the banking community in a relevant, credible environment — not simply generate visibility.</p></div><AudienceSplit variant="partners"/><div className="partner-proof-stats"><div><strong>15+</strong><span>Events</span></div><div><strong>20+</strong><span>CEE Countries</span></div><div><strong>2,500+</strong><span>Attendees</span></div><div><strong>100+</strong><span>Technology Partners</span></div></div></div></section>

  <section className="section-light bank-community-proof"><div className="shell"><div className="partner-intro"><div><p className="eyebrow dark">Who You&apos;ll Connect With</p><h2 className="section-heading-lines"><span>Banking Institutions</span><span>Across the Banking</span><span>CEE Community.</span></h2></div><p>Our network has brought together banking institutions from across Central &amp; Eastern Europe over multiple editions. The logos below represent organisations that form part of the wider Banking CEE community and are not a list of confirmed attendees for one specific event.</p></div><BankLogoGrid/></div></section>

  <section className="section-white" id="flagship"><div className="shell"><p className="eyebrow dark">Two Events. Two Distinct Experiences.</p><h2>Choose the Environment That Fits Your Objectives.</h2><p className="section-intro-copy">Banking CEE offers two established formats: the Expo for scale, breadth and regional reach; the Summit for focused senior-level engagement.</p><div className="partner-event-grid"><article className="partner-event expo-partner-event">
    <Image src="/images/expo-stage.webp" alt="Banking CEE Expo partner activation" fill className="cover"/><div className="partner-event-shade"/><div className="partner-event-copy"><span>Banking CEE Expo 2026 · Scale &amp; Regional Reach</span><h3>250+ Attendees · 20+ CEE Countries · 3 Stages</h3><p>Thought Leadership · Exhibition · Brand Visibility · 1:1 Meetings · Networking &amp; Hospitality</p><a href="/partnership-enquiry?event=expo-2026&source=partners-comparison">Explore Expo Partnership →</a></div></article><article className="partner-event summit-partner-event">
    <Image src="/images/summit-community.webp" alt="Digital Banking CEE Summit partner experience" fill className="cover"/><div className="partner-event-shade"/><div className="partner-event-copy"><span>Digital Banking CEE Summit 2027 · Focus &amp; Seniority</span><h3>100 Attendees · 75%+ C-Level, Directors &amp; Heads · 1 Stage</h3><p>Thought Leadership · Brand Visibility · 1:1 Meetings · Networking · Executive Engagement</p><a href="/partnership-enquiry?event=summit-2027&source=partners-comparison">Explore Summit Partnership →</a></div></article></div></div>
  </section>

  <section className="section-light" id="partnership-options"><div className="shell"><p className="eyebrow dark">Beyond Our Flagship Events</p><h2>Different Formats for Different Objectives.</h2><p className="section-intro-copy">Banking CEE partnerships extend beyond the flagship events, creating opportunities for more targeted engagement with the regional banking community.</p><div className="partner-format-list">
    <article><div className="partner-format-copy"><span>01 — FLAGSHIP EVENTS</span><h3>Banking CEE Expo &amp; Digital Banking CEE Summit</h3><ul><li>Thought leadership and speaking opportunities</li><li>Exhibition and brand visibility</li><li>1:1 meetings and networking</li><li>Regional engagement across the Banking CEE community</li></ul><p><strong>Great for:</strong> organisations looking for broader visibility, thought leadership and access to banking decision-makers across CEE.</p><a href="#flagship">Explore Flagship Events →</a></div><div className="partner-format-image"><Image src="/images/partner-events1.webp" alt="Flagship event partnership" fill className="cover"/></div></article>
    <article><div className="partner-format-copy"><span>02 — TAILORED EVENTS</span><h3>Your Audience. Your Topic. Your Event.</h3><ul><li>20–30 pre-qualified industry attendees</li><li>Premium dinner or roundtable formats</li><li>Dedicated topic and audience</li><li>Direct engagement in a focused environment</li></ul><p><strong>Great for:</strong> organisations looking for high-touch engagement with selected decision-makers around a specific topic, market or business objective.</p><a href="/partnership-enquiry?interest=tailored&source=partners-formats">Explore Tailored Events →</a></div><div className="partner-format-image"><Image src="/images/partner-tailored-event.webp" alt="Tailored Banking CEE event" fill className="cover"/></div></article>
    <article><div className="partner-format-copy"><span>03 — WEBINARS</span><h3>Take the Conversation Online.</h3><ul><li>Targeted topic and audience</li><li>Banking and industry perspectives</li><li>Interactive online discussion</li><li>Regional reach beyond physical events</li></ul><p><strong>Great for:</strong> organisations looking to showcase expertise, introduce new ideas or build thought leadership around a specific banking topic.</p><a href="/partnership-enquiry?interest=tailored&source=partners-formats">Explore Webinars →</a></div><div className="partner-format-image"><Image src="/images/partner-webinar1.webp" alt="Banking CEE thought leadership" fill className="cover"/></div></article>
  </div></div></section>

  <section className="section-white technology-proof"><div className="shell"><div className="partner-intro"><div><p className="eyebrow dark">Technology Partners Across CEE</p><h2>Trusted by Technology Companies Across the Banking CEE Network.</h2></div><p>Our partner community includes established international technology providers and specialist firms that have engaged with Banking CEE through previous events and partnership formats.</p></div><div className="trusted-partners"><PartnerLogoGrid/></div></div></section>

  <section className="section-navy partnership-closing"><div className="shell simple-cta"><div><p className="eyebrow">Let&apos;s Work Together</p><h2>Find the Right Partnership for Your Objectives.</h2><p>Tell us a little about your organisation, the opportunity you&apos;re interested in and what you would like to achieve. Our team will get back to you to discuss the most relevant options.</p></div><a className="btn btn-primary premium-cta" href="/partnership-enquiry?source=partners-bottom">Explore Partnership Opportunities →</a></div></section>
  <Footer/>
</main>}
